hub:
   port: 4444
   environments:
       - name:    "Firefox-3.5;en-us;WinXP"
         browser: "*firefox"
       - name:    "Firefox-default;en-us;MacOSX6"
         browser: "*chrome"
       - name:    "Firefox4b;en-us;MacOSX6"
         browser: "*firefox /Applications/Firefox4b.app/Contents/MacOS/firefox-bin"
       - name:    "Firefox-default-b;en-us;MacOSX6"
         browser: "*firefox"
       - name:    "Firefox-default;en-us;Linux"
         browser: "*firefox /home/mozilla/Desktop//firefox/firefox"
       - name:    "IE-7;en-us;WinXP"
         browser: "*iexplore"
       - name:    "Safari;en-us;MacOSX6"
         browser: "*safari"
       - name:    "Safari-4;en-us;MacOSX6"
         browser: "*safari"
       - name:     "Chrome;en-us;WinXP"
         browser:  "*googlechrome"
       - name:    "IE-8;en-us;Win7-second"
         browser: "*iexplore"
       - name:    "IE-8;en-us;Win7"
         browser: "*iexplore"
       - name:    "Chrome;en-us;MacOSX6"
         browser: "*googlechrome"
       - name:    "Firefox-default;en-us;WinXP"
         browser: "*firefoxproxy C:/Firefox36/firefox.exe"
       - name:    "Firefox-default;en-us;Win7-second"
         browser: "*firefox"
       - name:    "Firefox-default;en-us;Win7"
         browser: "*chrome"
       - name:    "*Minefield;en-us;WinXP"
         browser: "*firefox C:/Minefield/firefox.exe"
       - name:    "Firefox-yslow"
         browser: "*firefox C:/Firefox36/firefox.exe"
       - name:    "Firefox-3.5;en-us;MacOSX6"
         browser: "*firefox /Firefox.app/Contents/MacOS/firefox-bin"
       - name:    "*iexplore"
         browser: "*iexplore"
       - name:    "*iehta"
         browser: "*iehta"
       - name:    "*safari"
         browser: "*safari"
       - name:    "*opera"
         browser: "*opera"
       - name:    "*googlechrome"
         browser: "*googlechrome"
       - name:    "*firefoxproxy"
         browser: "*firefoxproxy"
       - name:    "*pifirefox"
         browser: "*pifirefox"
       - name:    "*iexploreproxy"
         browser: "*iexploreproxy"
       - name:    "*piiexplore"
         browser: "*piiexplore"
       - name:    "*safariproxy"
         browser: "*safariproxy"
