hub:
   environments:
       - name: "Firefox 3.6 on Mac OS X"
         browser: "*firefox /Applications/Firefox 3.6.app/Contents/MacOS/firefox-bin"
       - name: "Firefox 4 on Mac OS X"
         browser: "*firefox /Applications/Firefox 4.app/Contents/MacOS/firefox-bin"
       - name: "Firefox 5 on Mac OS X"
         browser: "*firefox /Applications/Firefox 5.app/Contents/MacOS/firefox-bin"
       - name: "Firefox Beta on Mac OS X"
         browser: "*firefox /Applications/Firefox Beta.app/Contents/MacOS/firefox-bin"
       - name: "Firefox Aurora on Mac OS X"
         browser: "*firefox /Applications/Aurora.app/Contents/MacOS/firefox-bin"
       - name: "Firefox Nightly on Mac OS X"
         browser: "*firefox /Applications/Nightly.app/Contents/MacOS/firefox-bin"
       - name: "Firefox 3.6 on Windows 7"
         browser: "*firefox C:/Program Files/Mozilla Firefox 3.6/firefox.exe"
       - name: "Firefox 4 on Windows 7"
         browser: "*firefox C:/Program Files/Mozilla Firefox 4/firefox.exe"
       - name: "Firefox 5 on Windows 7"
         browser: "*firefox C:/Program Files/Mozilla Firefox 5/firefox.exe"
       - name: "Firefox Beta on Windows 7"
         browser: "*firefox C:/Program Files/Mozilla Firefox Beta/firefox.exe"
       - name: "Firefox Aurora on Windows 7"
         browser: "*firefox C:/Program Files/Aurora/firefox.exe"
       - name: "Firefox Nightly on Windows 7"
         browser: "*firefox C:/Program Files/Nightly/firefox.exe"
       - name: "Internet Explorer 8 on Windows 7"
         browser: "*iexplore"
       - name: "Internet Explorer 9 on Windows 7"
         browser: "*iexplore"
