hub:
   environments:
       - name: "Firefox 3.6 on Mac OS X"
         browser: "*firefox /Applications/Firefox 3.6.app/Contents/MacOS/firefox-bin"
       - name: "Firefox 7 on Mac OS X"
         browser: "*firefox /Applications/Firefox 7.app/Contents/MacOS/firefox-bin"
       - name: "Firefox 8 on Mac OS X"
         browser: "*firefox /Applications/Firefox 8.app/Contents/MacOS/firefox-bin"
       - name: "Firefox Beta on Mac OS X"
         browser: "*firefox /Applications/Firefox Beta.app/Contents/MacOS/firefox-bin"
       - name: "Firefox Aurora on Mac OS X"
         browser: "*firefox /Applications/Aurora.app/Contents/MacOS/firefox-bin"
       - name: "Firefox Nightly on Mac OS X"
         browser: "*firefox /Applications/Nightly.app/Contents/MacOS/firefox-bin"
       - name: "Firefox 3.6 on Windows Vista"
         browser: "*firefox C:/Program Files/Mozilla Firefox 3.6/firefox.exe"
       - name: "Firefox 7 on Windows Vista"
         browser: "*firefox C:/Program Files/Mozilla Firefox 7/firefox.exe"
       - name: "Firefox 8 on Windows Vista"
         browser: "*firefox C:/Program Files/Mozilla Firefox 8/firefox.exe"
       - name: "Firefox Beta on Windows Vista"
         browser: "*firefox C:/Program Files/Mozilla Firefox Beta/firefox.exe"
       - name: "Firefox Aurora on Windows Vista"
         browser: "*firefox C:/Program Files/Aurora/firefox.exe"
       - name: "Firefox Nightly on Windows Vista"
         browser: "*firefox C:/Program Files/Nightly/firefox.exe"
       - name: "Internet Explorer 8 on Windows Vista"
         browser: "*iexplore"
       - name: "Internet Explorer 9 on Windows Vista"
         browser: "*iexplore"
       - name: "Firefox 3.6 on Windows 7"
         browser: "*firefox C:/Program Files/Mozilla Firefox 3.6/firefox.exe"
       - name: "Firefox 7 on Windows 7"
         browser: "*firefox C:/Program Files/Mozilla Firefox 7/firefox.exe"
       - name: "Firefox 8 on Windows 7"
         browser: "*firefox C:/Program Files/Mozilla Firefox 8/firefox.exe"
       - name: "Firefox Beta on Windows 7"
         browser: "*firefox C:/Program Files/Mozilla Firefox Beta/firefox.exe"
       - name: "Firefox Aurora on Windows 7"
         browser: "*firefox C:/Program Files/Aurora/firefox.exe"
       - name: "Firefox Nightly on Windows 7"
         browser: "*firefox C:/Program Files/Nightly/firefox.exe"
       - name: "Internet Explorer 8 on Windows 7"
         browser: "*iexplore"
       - name: "Internet Explorer 9 on Windows 7"
         browser: "*iexplore"
